theme: jekyll-theme-cayman
title: [Noah Jussila]
desc: SIEPR Predoctoral Research Fellow
navigation:
  - title: Home
    url: /home/
  - title: About Me
    url: /me/
    desc: About Me
  - title: CV
    url: /cv/
    desc: CV
